version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "06:00"  
      timezone: "Europe/Bucharest"
    open-pull-requests-limit: 10
    
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
